<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../libs/Mvc/Application.php';
AutoLoader::getInstance()->register();

/**
 * Test class for Mvc_Router_Route.
 * Generated by PHPUnit on 2010-03-01 at 12:54:22.
 */
class Mvc_Router_HttpRouterTest extends PHPUnit_Framework_TestCase
{




	protected function setUp()
	{

	}

	protected function tearDown()
	{
	}


	public function testSimpleRouting()
	{
		$router = new Mvc_Router_HttpRouter();
		$router->addRoute('test', new Mvc_Router_Route('/<controller>/<action>', array(), array()));

		$request = new Mvc_Controller_Request('/testController/testAction/');

		$router->route($request);

		$this->assertEquals('testController', $request->getControllerName());
		$this->assertEquals('testAction', $request->getActionName());

	}

	public function testRouteAssembling()
	{
		$router = new Mvc_Router_HttpRouter();
		$router->addRoute('test', new Mvc_Router_Route('/<controller>/<action>', array(), array()));

		$url = $router->assemble('test', array(
			'controller' => 'testController',
			'action'	=> 'testAction'
		));

		$this->assertEquals('/testController/testAction', $url);

	}

}